[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
build_src_flags = -O0 -I "${platformio.packages_dir}/framework-picosdk/lib/tinyusb/src"
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200

build_src_filter =
  +<*>
  +<${platformio.packages_dir}/framework-picosdk/lib/tinyusb/src/tusb.c>
  +<${platformio.packages_dir}/framework-picosdk/lib/tinyusb/src/common/tusb_fifo.c>
  +<${platformio.packages_dir}/framework-picosdk/lib/tinyusb/src/host/usbh.c>
  +<${platformio.packages_dir}/framework-picosdk/lib/tinyusb/src/host/hub.c>
  +<${platformio.packages_dir}/framework-picosdk/lib/tinyusb/src/class/hid/hid_host.c>
  +<${platformio.packages_dir}/framework-picosdk/lib/tinyusb/src/portable/raspberrypi/rp2040/hcd_rp2040.c>
  +<${platformio.packages_dir}/framework-picosdk/lib/tinyusb/src/portable/raspberrypi/rp2040/rp2040_usb.c>
